### ISSUE TITLE
RuntimeException: Error while preparing NBT wrapper classes.

### ISSUE THREAD

**Issue by mibby** [goncalomb/NBTEditor#12]
NBTEditor v2.3 dev 10 https://jenkins.androkai.net/job/NBTEditor/
Paper dev 1170 (Spigot 1.12.1)

Broke with minecraft update 1.12.1?
```
[13:31:10] [Server thread/INFO]: [NBTEditor] Enabling NBTEditor v2.3-SNAPSHOT
[13:31:10] [Server thread/ERROR]: [NBTEditor] Error preparing reflection objects
java.lang.RuntimeException: Error while preparing NBT wrapper classes.
	at com.goncalomb.bukkit.mylib.reflect.NBTBase.prepareReflection(NBTBase.java:52) ~[nbteditor-2.3-SNAPSHOT.jar:?]
	at com.goncalomb.bukkit.nbteditor.NBTEditor.onEnable(NBTEditor.java:72) [nbteditor-2.3-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [patched_1.12.1.jar:git-Paper-1170]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.12.1.jar:git-Paper-1170]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [patched_1.12.1.jar:git-Paper-1170]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:376) [patched_1.12.1.jar:git-Paper-1170]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:325) [patched_1.12.1.jar:git-Paper-1170]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) [patched_1.12.1.jar:git-Paper-1170]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) [patched_1.12.1.jar:git-Paper-1170]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) [patched_1.12.1.jar:git-Paper-1170]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:290) [patched_1.12.1.jar:git-Paper-1170]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.1.jar:git-Paper-1170]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.NoSuchMethodException: net.minecraft.server.v1_12_R1.TileEntity.a(net.minecraft.server.v1_12_R1.NBTTagCompound)
	at java.lang.Class.getMethod(Class.java:1786) ~[?:1.8.0_144]
	at com.goncalomb.bukkit.mylib.reflect.NBTUtils.prepareReflection(NBTUtils.java:86) ~[?:?]
	at com.goncalomb.bukkit.mylib.reflect.NBTBase.prepareReflection(NBTBase.java:50) ~[?:?]
	... 12 more
[13:31:10] [Server thread/ERROR]: [NBTEditor] This version of NBTEditor is not compatible with this version of Bukkit

```

**Comment by mibby** [comment]
@goncalomb Any ETA on a fix? :(


Tested again with Paper dev 1178 since it includes an upstream commit that modifies TileEntities.
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/19507baf8b7903427bc3efab7118de6e7c1c931e#nms-patches/TileEntityBrewingStand.patch
```
[23:45:00] [Server thread/INFO]: [NBTEditor] Enabling NBTEditor v2.3-SNAPSHOT
[23:45:00] [Server thread/ERROR]: [NBTEditor] Error preparing reflection objects
java.lang.RuntimeException: Error while preparing NBT wrapper classes.
	at com.goncalomb.bukkit.mylib.reflect.NBTBase.prepareReflection(NBTBase.java:52) ~[nbteditor-2.3-SNAPSHOT.jar:?]
	at com.goncalomb.bukkit.nbteditor.NBTEditor.onEnable(NBTEditor.java:72) [nbteditor-2.3-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [patched_1.12.1.jar:git-Paper-1178]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.12.1.jar:git-Paper-1178]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [patched_1.12.1.jar:git-Paper-1178]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:382) [patched_1.12.1.jar:git-Paper-1178]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:331) [patched_1.12.1.jar:git-Paper-1178]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) [patched_1.12.1.jar:git-Paper-1178]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) [patched_1.12.1.jar:git-Paper-1178]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) [patched_1.12.1.jar:git-Paper-1178]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:290) [patched_1.12.1.jar:git-Paper-1178]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.1.jar:git-Paper-1178]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.NoSuchMethodException: net.minecraft.server.v1_12_R1.TileEntity.a(net.minecraft.server.v1_12_R1.NBTTagCompound)
	at java.lang.Class.getMethod(Class.java:1786) ~[?:1.8.0_144]
	at com.goncalomb.bukkit.mylib.reflect.NBTUtils.prepareReflection(NBTUtils.java:86) ~[?:?]
	at com.goncalomb.bukkit.mylib.reflect.NBTBase.prepareReflection(NBTBase.java:50) ~[?:?]
	... 12 more
[23:45:00] [Server thread/ERROR]: [NBTEditor] This version of NBTEditor is not compatible with this version of Bukkit
```

**Comment by goncalomb** [comment]
That commit looks scary! But it should not affect the NBTEditor because we edit the underlying NBT data directly. It should work now on 1.12.1. Let me know of any other problems. Thanks.
