### ISSUE TITLE
NBTeditor error 1.12.1

### ISSUE THREAD

**Issue by noy98** [goncalomb/NBTEditor#14]
[21:26:38] [Server thread/INFO]: [NBTEditor] Enabling NBTEditor v2.3-SNAPSHOT
[21:26:38] [Server thread/ERROR]: [NBTEditor] Error preparing reflection objects
java.lang.RuntimeException: Error while preparing NBT wrapper classes.
	at com.goncalomb.bukkit.mylib.reflect.NBTBase.prepareReflection(NBTBase.java:52) ~[nbteditor-2.3-SNAPSHOT.jar:?]
	at com.goncalomb.bukkit.nbteditor.NBTEditor.onEnable(NBTEditor.java:72) [nbteditor-2.3-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [spigot.jar:git-Spigot-65e8124-963b19c]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-65e8124-963b19c]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot.jar:git-Spigot-65e8124-963b19c]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:380) [spigot.jar:git-Spigot-65e8124-963b19c]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:329) [spigot.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot.jar:git-Spigot-65e8124-963b19c]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_141]
Caused by: java.lang.NoSuchMethodException: net.minecraft.server.v1_12_R1.TileEntity.a(net.minecraft.server.v1_12_R1.NBTTagCompound)
	at java.lang.Class.getMethod(Unknown Source) ~[?:1.8.0_141]
	at com.goncalomb.bukkit.mylib.reflect.NBTUtils.prepareReflection(NBTUtils.java:86) ~[?:?]
	at com.goncalomb.bukkit.mylib.reflect.NBTBase.prepareReflection(NBTBase.java:50) ~[?:?]
	... 12 more
[21:26:38] [Server thread/ERROR]: [NBTEditor] This version of NBTEditor is not compatible with this version of Bukkit

**Comment by goncalomb** [comment]
The newer builds on Jenkins work on all 1.12 versions, [more info here](https://dev.bukkit.org/projects/nbteditor?comment=918).
