### ISSUE TITLE
1.14 Reflections Error

### ISSUE THREAD

**Issue by 14ercooper** [goncalomb/NBTEditor#37]
Attempting to use the plugin 1.14 yields fatal errors regarding reflections. The one which shows in the console on launch with the latest Spigot build is:

`
[16:36:54] [Server thread/ERROR]: [NBTEditor] Error preparing reflection objects
java.lang.RuntimeException: Error while preparing NBT wrapper classes.
	at com.goncalomb.bukkit.mylib.reflect.NBTBase.prepareReflection(NBTBase.java:52) ~[nbteditor-3.1.1-SNAPSHOT.jar:?]
	at com.goncalomb.bukkit.nbteditor.NBTEditor.onEnable(NBTEditor.java:70) [nbteditor-3.1.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) [server.jar:git-Spigot-0c02b0c-e879c44]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:346) [server.jar:git-Spigot-0c02b0c-e879c44]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:408) [server.jar:git-Spigot-0c02b0c-e879c44]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:458) [server.jar:git-Spigot-0c02b0c-e879c44]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:372) [server.jar:git-Spigot-0c02b0c-e879c44]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:440) [server.jar:git-Spigot-0c02b0c-e879c44]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258) [server.jar:git-Spigot-0c02b0c-e879c44]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:758) [server.jar:git-Spigot-0c02b0c-e879c44]
	at java.lang.Thread.run(Thread.java:844) [?:?]
Caused by: java.lang.NoSuchMethodException: net.minecraft.server.v1_14_R1.ChunkRegionLoader.a(net.minecraft.server.v1_14_R1.NBTTagCompound, net.minecraft.server.v1_14_R1.World, double, double, double, boolean)
	at java.lang.Class.getMethod(Class.java:2067) ~[?:?]
	at com.goncalomb.bukkit.mylib.reflect.NBTUtils.prepareReflection(NBTUtils.java:111) ~[?:?]
	at com.goncalomb.bukkit.mylib.reflect.NBTBase.prepareReflection(NBTBase.java:50) ~[?:?]
	... 10 more
[16:36:54] [Server thread/ERROR]: [NBTEditor] This version of NBTEditor is not compatible with this version of Bukkit`

**Comment by goncalomb** [comment]
I'm starting to work on a 1.14 version. Build #45 should already work on 1.14.X.
This is a early version with little testing, backup your worlds/BoSs, use at own risk.
https://jenkins.androkai.net/job/NBTEditor/
New entities and variables are missing on this build. I need to research what as been added as I don't really follow any Minecraft updates anymore. :(
Meanwhile use this thread to report any issues. Thanks.

**Comment by Inversil** [comment]
Hey goncalomb, thank you for your work but.. your website is dead!!

**Comment by goncalomb** [comment]
The latest builds on the new Jenkins server (https://jenkins.goncalomb.com/job/NBTEditor/) are compatible with 1.14 and 1.15, more features like missing variables will be added later.
