### ISSUE TITLE
The 1.15 Update

### ISSUE THREAD

**Issue by enterih** [goncalomb/NBTEditor#43]
It's just released and Plugin is broken (didn't load).

Just an Issue to let you know and hope we can use it soon (hope you will add an alternative jenkins)

**Comment by mibby** [comment]
@goncalomb Whenever you get the chance to add 1.15.1 support. :)

```
[03:28:01] [Server thread/INFO]: [NBTEditor] Enabling NBTEditor v3.2-SNAPSHOT
[03:28:01] [Server thread/ERROR]: [NBTEditor] Error preparing reflection objects
java.lang.RuntimeException: Error while preparing NBT wrapper classes.
	at com.goncalomb.bukkit.mylib.reflect.NBTBase.prepareReflection(NBTBase.java:52) ~[?:?]
	at com.goncalomb.bukkit.nbteditor.NBTEditor.onEnable(NBTEditor.java:70) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[paperclip.jar:git-Purpur-348]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[paperclip.jar:git-Purpur-348]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[paperclip.jar:git-Purpur-348]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:468) ~[paperclip.jar:git-Purpur-348]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:382) ~[paperclip.jar:git-Purpur-348]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:482) ~[paperclip.jar:git-Purpur-348]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:299) ~[paperclip.jar:git-Purpur-348]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:886) ~[paperclip.jar:git-Purpur-348]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: java.lang.NoSuchMethodException: net.minecraft.server.v1_15_R1.NBTTagByte.<init>(byte)
	at java.lang.Class.getConstructor0(Class.java:3082) ~[?:1.8.0_232]
	at java.lang.Class.getConstructor(Class.java:1825) ~[?:1.8.0_232]
	at com.goncalomb.bukkit.mylib.reflect.NBTTypes.<init>(NBTTypes.java:86) ~[?:?]
	at com.goncalomb.bukkit.mylib.reflect.NBTTypes.registerNew(NBTTypes.java:49) ~[?:?]
	at com.goncalomb.bukkit.mylib.reflect.NBTTypes.prepareReflection(NBTTypes.java:39) ~[?:?]
	at com.goncalomb.bukkit.mylib.reflect.NBTBase.prepareReflection(NBTBase.java:49) ~[?:?]
	... 10 more
[03:28:01] [Server thread/ERROR]: [NBTEditor] This version of NBTEditor is not compatible with this version of Bukkit
```

**Comment by enterih** [comment]
Does give any update for 1.15.2?

**Comment by Combustible** [comment]
Added pull request #47 for this. You can build it locally and use it for 1.15

**Comment by goncalomb** [comment]
The latest builds on the new Jenkins server (https://jenkins.goncalomb.com/job/NBTEditor/) are compatible with 1.14 and 1.15, more features like missing variables will be added later.
