### ISSUE TITLE
1.12.2 Spigot bukkit error

### ISSUE THREAD

**Issue by Evan-SY-Jung** [goncalomb/NBTEditor#48]
[NBTEditor] Enabling NBTEditor v3.0
[05:03:17] [Server thread/ERROR]: [NBTEditor] Error preparing reflection objects
java.lang.NullPointerException: null
        at com.goncalomb.bukkit.mylib.reflect.BukkitReflect.prepareReflection(BukkitReflect.java:72) ~[nbteditor-3.0.jar:?]
        at com.goncalomb.bukkit.nbteditor.NBTEditor.onEnable(NBTEditor.java:71) [nbteditor-3.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [JavaPlugin.class:git-CatServer-1.12.2-3440193]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:328) [JavaPluginLoader.class:git-CatServer-1.12.2-3440193]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [SimplePluginManager.class:git-CatServer-1.12.2-3440193]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:436) [CraftServer.class:git-CatServer-1.12.2-3440193]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:384) [CraftServer.class:git-CatServer-1.12.2-3440193]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:391) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:327) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:602) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[05:03:17] [Server thread/ERROR]: [NBTEditor] This version of NBTEditor is not compatible with this version of Bukkit

I used old (both 1.12) and newest (1.13) versions and those messages are keep poping up.
I am using spigot server and it is 1.12.2.

**Comment by Combustible** [comment]
NBTEditor hooks into minecraft at a lower level than "average" bukkit plugins. It depends on the minecraft base code having specific names and being in specific locations. The server needs to be compatible with this (specifically, it needs to be based on Spigot and using the spigot deobfuscation mappings).

I had never heard of CatServer before - it looks like a poorly supported combination of bukkit and forge APIs. They almost certainly had to modify the base files that this plugin depends on to get that to work - meaning I doubt you will ever get NBTEditor working on a CatServer platform. It would need to be specifically ported to work on CatServer.
