### ISSUE TITLE
MC 1.12 Support

### ISSUE THREAD

**Issue by mibby** [goncalomb/NBTEditor#9]
@goncalomb Heads up. NBTEditor needs to be updated to support 1.12.

```
[23:00:05] [Server thread/INFO]: [NBTEditor] Enabling NBTEditor v2.2-SNAPSHOT
[23:00:05] [Server thread/ERROR]: [NBTEditor] Error preparing reflection objects
java.lang.RuntimeException: Error while preparing NBT wrapper classes.
	at com.goncalomb.bukkit.mylib.reflect.NBTBase.prepareReflection(NBTBase.java:53) ~[nbteditor-2.2-SNAPSHOT.jar:?]
	at com.goncalomb.bukkit.nbteditor.NBTEditor.onEnable(NBTEditor.java:70) [nbteditor-2.2-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [patched_1.12-pre6.jar:git-Paper-"adab11a1"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.12-pre6.jar:git-Paper-"adab11a1"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [patched_1.12-pre6.jar:git-Paper-"adab11a1"]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:379) [patched_1.12-pre6.jar:git-Paper-"adab11a1"]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:329) [patched_1.12-pre6.jar:git-Paper-"adab11a1"]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:438) [patched_1.12-pre6.jar:git-Paper-"adab11a1"]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:399) [patched_1.12-pre6.jar:git-Paper-"adab11a1"]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [patched_1.12-pre6.jar:git-Paper-"adab11a1"]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:276) [patched_1.12-pre6.jar:git-Paper-"adab11a1"]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:612) [patched_1.12-pre6.jar:git-Paper-"adab11a1"]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.NoSuchMethodException: net.minecraft.server.v1_12_R1.Entity.e(net.minecraft.server.v1_12_R1.NBTTagCompound)
	at java.lang.Class.getMethod(Unknown Source) ~[?:1.8.0_131]
	at com.goncalomb.bukkit.mylib.reflect.NBTUtils.prepareReflection(NBTUtils.java:78) ~[?:?]
	at com.goncalomb.bukkit.mylib.reflect.NBTBase.prepareReflection(NBTBase.java:51) ~[?:?]
	... 12 more
[23:00:05] [Server thread/ERROR]: [NBTEditor] This version of NBTEditor is not compatible with this version of Bukkit
```

**Comment by goncalomb** [comment]
Thanks for information, I'll try to update it soon.

**Comment by mibby** [comment]
Error on official final release 1.12 build.

```
[21:29:00] [Server thread/INFO]: [NBTEditor] Enabling NBTEditor v2.2-SNAPSHOT
[21:29:00] [Server thread/ERROR]: [NBTEditor] Error preparing reflection objects
java.lang.RuntimeException: Error while preparing NBT wrapper classes.
	at com.goncalomb.bukkit.mylib.reflect.NBTBase.prepareReflection(NBTBase.java:53) ~[nbteditor-2.2-SNAPSHOT.jar:?]
	at com.goncalomb.bukkit.nbteditor.NBTEditor.onEnable(NBTEditor.java:70) [nbteditor-2.2-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [patched_1.12.jar:git-Paper-1106]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.12.jar:git-Paper-1106]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [patched_1.12.jar:git-Paper-1106]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:379) [patched_1.12.jar:git-Paper-1106]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:329) [patched_1.12.jar:git-Paper-1106]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:438) [patched_1.12.jar:git-Paper-1106]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:399) [patched_1.12.jar:git-Paper-1106]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [patched_1.12.jar:git-Paper-1106]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:276) [patched_1.12.jar:git-Paper-1106]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:612) [patched_1.12.jar:git-Paper-1106]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.NoSuchMethodException: net.minecraft.server.v1_12_R1.Entity.e(net.minecraft.server.v1_12_R1.NBTTagCompound)
	at java.lang.Class.getMethod(Unknown Source) ~[?:1.8.0_131]
	at com.goncalomb.bukkit.mylib.reflect.NBTUtils.prepareReflection(NBTUtils.java:78) ~[?:?]
	at com.goncalomb.bukkit.mylib.reflect.NBTBase.prepareReflection(NBTBase.java:51) ~[?:?]
	... 12 more
[21:29:00] [Server thread/ERROR]: [NBTEditor] This version of NBTEditor is not compatible with this version of Bukkit
```

**Comment by enterih** [comment]
Any possible Day, that u update to 1.12 @goncalomb  ?

**Comment by goncalomb** [comment]
It should be compatible with 1.12 now, see the [mc-1.12](https://github.com/goncalomb/NBTEditor/tree/mc-1.12) branch. As always the older BoSs are compatible. Parrots are also supported.
